### ISSUE TITLE
Error connecting to localhost and finding processes

### ISSUE THREAD

**Issue by jagged00** [hemanthl7/cheat-engine-ps4-server#2]
Error while GetProcessMaps
System.NullReferenceException: Object reference not set to an instance of an object.
   at CEServerPS4.PS4API.ToolHelp.InitModuleList(ProcessMap pm)
   at CEServerPS4.PS4API.ToolHelp.CreateToolhelp32Snapshot(SnapshotFlags dwFlags, UInt32 th32ProcessID)
   at CEServerPS4.CheatEnginePackets.C2S.CreateToolHelp32SnapshotCommand.Process()
   at CEServerPS4.CheatEnginePackets.C2S.CheatEngineCommand`1.ProcessAndGetBytes()
   at CEServerPS4.CheatEnginePackets.PacketManager.ProcessAndGetBytes(ICheatEngineCommand command)
   at CEServerPS4.CheatEngineServer.HandleReceivedClient(TcpClient client): Object reference not set to an instance of an object.
   at CEServerPS4.PS4API.ToolHelp.InitModuleList(ProcessMap pm)
   at CEServerPS4.PS4API.ToolHelp.CreateToolhelp32Snapshot(SnapshotFlags dwFlags, UInt32 th32ProcessID)
   at CEServerPS4.CheatEnginePackets.C2S.CreateToolHelp32SnapshotCommand.Process()
   at CEServerPS4.CheatEnginePackets.C2S.CheatEngineCommand`1.ProcessAndGetBytes()
   at CEServerPS4.CheatEnginePackets.PacketManager.ProcessAndGetBytes(ICheatEngineCommand command)
   at CEServerPS4.CheatEngineServer.HandleReceivedClient(TcpClient client)

**Comment by hemanthl7** [comment]
please close console and cheat engine completely, reconnect it should work

**Comment by jagged00** [comment]
> please close console and cheat engine completely, reconnect it should work

still doesn't work the process list is just blank

**Comment by hemanthl7** [comment]
may i know which version of CE you are using and PS4 payload you are Using

**Comment by jagged00** [comment]
> may i know which version of CE you are using and PS4 payload you are Using

9.00 goldhen
7.3 CE

**Comment by hemanthl7** [comment]
can you use CE 7.4 or you can download this here with new release.
https://github.com/hemanthl7/cheat-engine-ps4-server/releases/tag/1.0.2

**Comment by jagged00** [comment]
> can you use CE 7.4 or you can download this here with new release. https://github.com/hemanthl7/cheat-engine-ps4-server/releases/tag/1.0.2

downloaded newest version sent payload, did the same steps as before connected successfully but when I open cheat engine connecting to the local host the list is just blank

**Comment by jagged00** [comment]
![piv](https://user-images.githubusercontent.com/100363925/155603299-60ffe2c6-2b16-4331-8f79-1683964bbde2.JPG)

**Comment by hemanthl7** [comment]
can write detailed steps how this happened?
first do restart ps4 and close cheat engine and ceseverps4  
try to connect and give error i will simulate it in my system and see if it happening

**Comment by jagged00** [comment]
> can write detailed steps how this happened? first do restart ps4 and close cheat engine and ceseverps4 try to connect and give error i will simulate it in my system and see if it happening

1.Cut off ps4, restart.
2.Rejailbreak console with usb
3.Enable binloader and the port.
4.Launch game
5.Tried using https://karo218.ir/900/index.html as well as ps4cheater ps4debug and both lead to the same result as above.
5.I proceed to run cmd in the folders dir then proceed with the normal settings to open up the program and connect it to my ps4 entering my ip address. I give public as well as private network access to the program.
6.I launch cheat engine click network enter localhost in the empty box and leave the other default. what results is the blank list you see above no matter how long I wait.

**Comment by hemanthl7** [comment]
weird it says connected still you are not getting processlist

**Comment by jagged00** [comment]
> weird it says connected still you are not getting processlist

does network access of cheat engine matter? such as public or private?

**Comment by hemanthl7** [comment]
are you able connect cheat engine?

**Comment by jagged00** [comment]
> are you able connect ps4 cheater?

yes, i've tried connecting cheat engine after connecting ps4 cheater and that doesn't work either

**Comment by hemanthl7** [comment]
then there is some issue with your network.
https://github.com/hemanthl7/cheat-engine-ps4-server/releases/download/1.0.2/CEServerPS4.1.0.2.zip
I have updated release file.
please redownload and connect and give me, application.log file generated by app

**Comment by hemanthl7** [comment]
https://github.com/hemanthl7/cheat-engine-ps4-server/releases/tag/1.0.3

**Comment by jagged00** [comment]
> https://github.com/hemanthl7/cheat-engine-ps4-server/releases/tag/1.0.3

System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at CEServerPS4.CheatEnginePackets.PacketManager.ReadNextCommand(BinaryReader reader)
   at CEServerPS4.CheatEngineServer.HandleReceivedClient(TcpClient client): Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at CEServerPS4.CheatEnginePackets.PacketManager.ReadNextCommand(BinaryReader reader)
   at CEServerPS4.CheatEngineServer.HandleReceivedClient(TcpClient client)

**Comment by hemanthl7** [comment]
when you close cheat engine without close ps4 cesever this occurs

**Comment by hemanthl7** [comment]
feel free to this issue again if you are facing

**Comment by jagged00** [comment]
Hello, it works now just commenting to let you know that if cheat engine is checked only show processes for current user (right click) it won't display all processes.

**Comment by hemanthl7** [comment]
cheat engine check button is used for cheat engine which is given with CE Server in the realease no other purpose

**Comment by hemanthl7** [comment]
can you send screen shot, i will investigate
